= Getting Started

== Overview

This getting started guide provides instructions for setting up Wayk Den on a Windows Server 2019 Core + Containers virtual machine instance in Azure. This guide can also be followed for installation on a regular Windows Server 2019 Core virtual machine outside of Azure with minimal ajustments.

== Instructions

Start the docker service if it is not currently running:
----
$ Get-Service | Where-Object { $_.Name -Like 'docker' }
$ Start-Service -Name docker
----

Install the WaykDen module:
----
$ Install-Module -Name WaykDen -Force
----

Import the WaykDen module, create a new directory for Wayk Den files and move to it:
----
$ Import-Module -Name WaykDen
$ mkdir ~/den-test
$ cd ~/den-test
----

For the purpose of this guide, I will be using the DNS name 'den.buzzword.marketing' which was configured to point to my Azure VM (40.121.21.221)

Create a new Wayk Den configuration and then launch Wayk Den:
----
> $DenUrl = 'http://den.buzzword.marketing:80'
> New-WaykDenConfig -Realm buzzword.marketing -ExternalUrl $DenUrl -ListenerUrl $DenUrl
> Start-WaykDen -Verbose
----

The first launch will pull all docker images based on Windows Server Core, which can take a while because of their large size.
