= Getting Started

== Overview

This getting started guide provides instructions for setting up Wayk Den on a Windows Server 2019 Core + Containers virtual machine instance in Azure. This guide can also be followed for installation on a regular Windows Server 2019 Core virtual machine outside of Azure with minimal ajustments.

== Instructions

Install or update NuGet and PowerShellGet:
----
$ Install-PackageProvider -Name NuGet -Force
$ Install-Module -Name PowerShellGet -Force
----

Check if the Windows Server 'Containers' feature is installed, then install it:
----
$ Get-WindowsFeature | Where-Object { $_.Name -Like 'Containers' }
$ Install-WindowsFeature -Name Containers -Restart
----

Install the Microsoft Docker provider:
----
$ Install-Module -Name DockerMsftProvider -Force
$ Install-Package -Name docker -ProviderName DockerMsftProvider -Force
----

Start the docker service if it is not currently running:
----
$ Get-Service | Where-Object { $_.Name -Like 'docker' }
$ Start-Service -Name docker
----

Install the WaykDen module:
----
$ Install-Module -Name WaykDen -Force
----

Import the WaykDen module, create a new directory for Wayk Den files and move to it:
----
$ Import-Module -Name WaykDen
$ mkdir ~/den-test
$ cd ~/den-test

Create a new Wayk Den configuration and then launch Wayk Den:
----
$ New-WaykDenConfig -Realm windjammer.local -ExternalUrl http://localhost:4000
$ Start-WaykDen -Verbose
----

The first launch will pull all docker images based on Windows Server Core, which can take a while.

TODO:
* Improve docker pull options + responsiveness
